[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1_000_000
solc = '0.8.17'
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/ds-test/src/',
]
# for compatibility with token contracts deployed with 0.8.20 on Ethereum mainnet
# should not affect local compilation and simulation of non-Shanghai chains
evm_version = 'shanghai'

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_GOERLI}" }
polygon = { key = "${ETHERSCAN_POLYGON}" }
mumbai = {key = "${ETHERSCAN_MUMBAI}"}
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
